export enum AccessType {
  STATEMENTS_LOAD_FILE= 'STATEMENTS_LOAD_FILE',
  STATEMENTS_TEST_LOAD_LOB = 'STATEMENTS_TEST_LOAD_LOB',
  STATEMENTS_TEST_OPEN_LOB = 'STATEMENTS_TEST_OPEN_LOB',
  STATEMENTS_HISTORY_SEARCH = 'STATEMENTS_HISTORY_SEARCH',
  STATEMENTS_HISTORY_LOAD_LOB = 'STATEMENTS_HISTORY_LOAD_LOB',
  STATEMENTS_HISTORY_OPEN_LOB = 'STATEMENTS_HISTORY_OPEN_LOB',
}

export interface AccessObj {
  created: any,
  userId: string,
  what: AccessType,
  patientId?: string,
  ltrId?: string,
}
